[package]
name = "taylorlyricguessingrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.7.2"
edit-distance = "2.1.0"
rand = "0.8.5"
colored = "2.0.0"
